### ISSUE TITLE
Do not understand this logic

### ISSUE THREAD

**Issue by Neytrino-OnLine** [Mathnerd314/page-translator#4]
If option "Always show translate icon in the URL bar" activated - the icon & menu item shown & works...
https://cdn1.savepice.ru/uploads/2019/3/1/bd002ae84351f8c77d88488c098ddc9b-full.png
But if not - the menu item becomes inactive...
https://cdn1.savepice.ru/uploads/2019/3/1/82c1ed173c41296f747ceea0b4591416-full.png
Is it bug?

**Comment by Mathnerd314** [comment]
Sorry, the photos have expired. Github has built-in image uploading. I would suggest using that.

Regarding the menu item, it is inactive when the page is detected to be in a known language, the logic is here:
https://github.com/Mathnerd314/page-translator/blob/master/background.js#L90
This is so that the icon is not shown all the time but only when needed.
