### ISSUE TITLE
[Request] For security reasons, framing is not allowed.

### ISSUE THREAD

**Issue by gaveitatry** [Mathnerd314/page-translator#7]
This popup is annoying.  Can you provide an option to disable it?  I don't want or need to see it every time that I translate a page, especially when the translated pages successfully load properly.  It's just an annoying prompt that doesn't serve any real purpose.  Makes my experience worse instead of better.

**Comment by Mathnerd314** [comment]
My extension does not contain anything like that. From googling it seems to be a common JavaScript message. Which page(s) specifically are you encountering it on?

**Comment by gaveitatry** [comment]
I was testing it on a random GitHub page that was in German.
https://github.com/Endor8/userChrome.js/tree/master/userChrome

Google Translate says that it is already in English, so I've been using Bing or Microsoft in all the Translator web extensions that I've tried.  And in all of them, I get that popup.

**Comment by Mathnerd314** [comment]
Yeah, there is code in https://github.githubassets.com/assets/github-bootstrap-e8bc289d.js, roughly like:
```
if (<loaded inside a frame>) {
  alert("For security reasons, framing is not allowed.");
  top.location.replace(document.location)
}
```
Since the web versions of Google Translate and Microsoft Bing use frames they trigger this. 

One solution is to do the translation inline on the page, like the Chrome browser [does](https://cs.chromium.org/chromium/src/components/translate/core/browser/translate_script.cc) and like the [old](https://github.com/jeremiahlee/page-translator) Page Translator extension does, but those won't pass AMO's review policies because they inject remote code. If you want to go down that road your best bet is to get a Bing Translate [API Key](https://www.microsoft.com/en-us/translator/business/trial/#get-started) and try to get Firefox's [built-in translation system](https://www.ghacks.net/2018/09/09/mozilla-working-on-google-translate-integration-in-firefox/) working. There are some API preferences to set, found [here](https://hg.mozilla.org/mozilla-central/file/tip/browser/components/translation/BingTranslator.jsm#l379).  

But I think the easier solution is to remove the alert functionality using a TamperMonkey script (probably works in other *monkeys, but I haven't tried):
```
// ==UserScript==
// @name         Disable framing popup
// @match        https://translate.googleusercontent.com/*
// @match        https://www.translatoruser-int.com/*
// @grant        none
// @run-at       document-start
// ==/UserScript==

window.alert = function() {};
```

**Comment by gaveitatry** [comment]
Thank you for all the valuable information!  Yeah, I figured there was a chance that it was an AMO restriction, but I thought that I would ask just to be sure.  I'm liking that user script suggestion.  I'm going to give it a try soon.

Do you think you can add "Translate this Page" to the context menu?  Like when a person right clicks a website?  if so, that would be absolutely wonderful and then this web extension would truly be perfect.  I know it is possible because I tried other Firefox extensions that had that option in the context menu.  If you add the feature... well I can't wait.  I hope you update the extension soon with that feature.

Again, thanks for the information.  I'm going to try those things you suggested, starting with the user script first.

**Comment by gaveitatry** [comment]
Ha ha.  Yes!  The user script worked perfectly in ViolentMonkey.  It's my first time using ViolentMonkey, by the way.  I was using GreaseMonkey 3 on Firefox 56.0.2, but I'm trying to make the switch to Quantum 66.0.5 now.  I would have tried GreaseMonkey 4, but there were some problems with it.  Like, for one, it doesn't even have word wrap out-of-the-box.  TamperMonkey seemed better than GreaseMonkey 4, but I fell in love with ViolentMonkey's interface.
